DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS countries;


CREATE TABLE IF NOT EXISTS countries (
	country_name			VARCHAR(64) 	PRIMARY KEY);

CREATE TABLE IF NOT EXISTS customers (
	customer_id 				INTEGER 		PRIMARY KEY);

CREATE TABLE IF NOT EXISTS products (
	stock_code 			VARCHAR(12) 	PRIMARY KEY, 
	description 	VARCHAR(128) 	
);

CREATE TABLE IF NOT EXISTS invoices (
	invoice_no 		VARCHAR(12) 	NOT NULL,
	stock_code		VARCHAR(12)		NOT NULL
		REFERENCES products (stock_code) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	qty				INTEGER			NOT NULL,
	invoice_date	TIMESTAMP		NOT NULL,
	price_per_unit 	NUMERIC(10,2)	NOT NULL,
	customer_id 	INTEGER		
		REFERENCES customers (customer_id) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	country_name	VARCHAR(64) 	NOT NULL
		REFERENCES countries (country_name) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
	
);